package store

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

// CreateAppointmentInput carries the fields required to insert an appointment.
// The row ID (UUID v4) is generated by the store layer. ManagementToken is
// optional (public bookings only) and generated by the service layer.
type CreateAppointmentInput struct {
	StoreID         string
	ClientName      string
	ClientPhone     string
	ClientEmail     string
	DateTime        time.Time // UTC
	Service         *string
	Status          AppointmentStatus
	Notes           *string
	ManagementToken *string
}

// AppointmentFilter constrains ListAppointments. Nil fields are ignored.
// Start/End bound date_time (inclusive/exclusive) in UTC, so the caller
// converts a local day to a UTC window first.
type AppointmentFilter struct {
	Start  *time.Time
	End    *time.Time
	Status *AppointmentStatus
}

// scanAppointment reads a single appointment row in appointmentColumns order.
func scanAppointment(row pgx.Row) (Appointment, error) {
	var a Appointment
	var status string
	err := row.Scan(
		&a.ID, &a.StoreID, &a.ClientName, &a.ClientPhone, &a.ClientEmail,
		&a.DateTime, &a.Service, &status, &a.Notes, &a.ManagementToken,
	)
	a.Status = AppointmentStatus(status)
	return a, err
}

// AppointmentsInWindow returns appointments for a store whose date_time falls
// in the half-open UTC window [start, end).
func (db *DB) AppointmentsInWindow(ctx context.Context, storeID string, start, end time.Time) ([]Appointment, error) {
	return appointmentsInWindow(ctx, db.pool, storeID, start, end, "")
}

// AppointmentsInWindowExcluding is AppointmentsInWindow minus the appointment
// with the given id (used by reschedule so the appointment does not count
// against its own capacity).
func (db *DB) AppointmentsInWindowExcluding(ctx context.Context, storeID string, start, end time.Time, excludeID string) ([]Appointment, error) {
	return appointmentsInWindow(ctx, db.pool, storeID, start, end, excludeID)
}

// appointmentsInWindow reads through the given querier (pool or tx).
func appointmentsInWindow(ctx context.Context, q querier, storeID string, start, end time.Time, excludeID string) ([]Appointment, error) {
	query := `SELECT ` + appointmentColumns + `
		FROM appointments
		WHERE store_id = $1 AND date_time >= $2 AND date_time < $3`
	args := []any{storeID, start, end}
	if excludeID != "" {
		query += ` AND id <> $4`
		args = append(args, excludeID)
	}
	query += ` ORDER BY date_time`

	rows, err := q.Query(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []Appointment{}
	for rows.Next() {
		a, err := scanAppointment(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, a)
	}
	return out, rows.Err()
}

// CreateAppointment inserts a new appointment (generating its UUID v4 id) and
// returns it.
func (db *DB) CreateAppointment(ctx context.Context, in CreateAppointmentInput) (Appointment, error) {
	return createAppointment(ctx, db.pool, in)
}

// GetAppointmentByID returns the appointment with the given id, or
// pgx.ErrNoRows.
func (db *DB) GetAppointmentByID(ctx context.Context, id string) (Appointment, error) {
	row := db.pool.QueryRow(ctx, `SELECT `+appointmentColumns+` FROM appointments WHERE id = $1`, id)
	return scanAppointment(row)
}

// createAppointment inserts through the given querier (pool or tx).
func createAppointment(ctx context.Context, q querier, in CreateAppointmentInput) (Appointment, error) {
	id := uuid.NewString()
	row := q.QueryRow(ctx, `
		INSERT INTO appointments (id, store_id, client_name, client_phone,
			client_email, date_time, service, status, notes, management_token)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
		RETURNING `+appointmentColumns,
		id, in.StoreID, in.ClientName, in.ClientPhone, in.ClientEmail,
		in.DateTime, in.Service, string(in.Status), in.Notes, in.ManagementToken,
	)
	return scanAppointment(row)
}

// UpdateAppointmentStatus changes an appointment's status and returns the
// updated row, or pgx.ErrNoRows if the appointment does not exist.
func (db *DB) UpdateAppointmentStatus(ctx context.Context, id string, status AppointmentStatus) (Appointment, error) {
	row := db.pool.QueryRow(ctx, `
		UPDATE appointments SET status = $2, updated_at = now()
		WHERE id = $1
		RETURNING `+appointmentColumns, id, string(status))
	return scanAppointment(row)
}

// RescheduleAppointment moves an appointment to a new date_time (UTC) and
// returns the updated row, or pgx.ErrNoRows if the appointment does not exist.
func (db *DB) RescheduleAppointment(ctx context.Context, id string, dateTime time.Time) (Appointment, error) {
	row := db.pool.QueryRow(ctx, `
		UPDATE appointments SET date_time = $2, updated_at = now()
		WHERE id = $1
		RETURNING `+appointmentColumns, id, dateTime)
	return scanAppointment(row)
}

// ListAppointments returns appointments for a store matching the optional
// date range and status filters, ordered by date_time ascending.
func (db *DB) ListAppointments(ctx context.Context, storeID string, f AppointmentFilter) ([]Appointment, error) {
	where := "store_id = $1"
	args := []any{storeID}
	add := func(cond string, val any) {
		args = append(args, val)
		where += fmt.Sprintf(" AND %s $%d", cond, len(args))
	}
	if f.Start != nil {
		add("date_time >=", *f.Start)
	}
	if f.End != nil {
		add("date_time <", *f.End)
	}
	if f.Status != nil {
		add("status =", string(*f.Status))
	}

	rows, err := db.pool.Query(ctx, `SELECT `+appointmentColumns+`
		FROM appointments WHERE `+where+`
		ORDER BY date_time`, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	out := []Appointment{}
	for rows.Next() {
		a, err := scanAppointment(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, a)
	}
	return out, rows.Err()
}
