package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// Session is a single sessions row: the hashed login token, the CSRF token
// bound to it, and its expiry window. It is never serialized to clients.
type Session struct {
	ID        string
	UserID    string
	TokenHash string
	CSRFToken string
	ExpiresAt time.Time
	CreatedAt time.Time
}

// CreateSessionInput carries the fields required to create a session. The row
// ID (UUID v4) is generated by the store layer.
type CreateSessionInput struct {
	UserID    string
	TokenHash string
	CSRFToken string
	ExpiresAt time.Time
}

// CreateSession inserts a new session and returns the persisted row.
func (db *DB) CreateSession(ctx context.Context, in CreateSessionInput) (Session, error) {
	id := uuid.NewString()
	row := db.pool.QueryRow(ctx, `
		INSERT INTO sessions (id, user_id, token_hash, csrf_token, expires_at)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING id, user_id, token_hash, csrf_token, expires_at, created_at`,
		id, in.UserID, in.TokenHash, in.CSRFToken, in.ExpiresAt)

	var s Session
	if err := row.Scan(&s.ID, &s.UserID, &s.TokenHash, &s.CSRFToken, &s.ExpiresAt, &s.CreatedAt); err != nil {
		return Session{}, err
	}
	return s, nil
}

// GetActorByTokenHash resolves the authenticated actor for a session token
// hash, joining users for the profile. Expired or absent sessions do not
// resolve and return pgx.ErrNoRows.
func (db *DB) GetActorByTokenHash(ctx context.Context, tokenHash string) (Actor, error) {
	row := db.pool.QueryRow(ctx, `
		SELECT u.id, u.name, u.email, u.role
		FROM sessions s
		JOIN users u ON u.id = s.user_id
		WHERE s.token_hash = $1 AND s.expires_at > now()`, tokenHash)

	var a Actor
	var name, email *string
	if err := row.Scan(&a.ID, &name, &email, &a.Role); err != nil {
		return Actor{}, err
	}
	a.Name = strOrEmpty(name)
	a.Email = strOrEmpty(email)
	return a, nil
}

// DeleteSessionByTokenHash removes the session for a token hash. It is
// idempotent: deleting a non-existent session is not an error.
func (db *DB) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := db.pool.Exec(ctx, `DELETE FROM sessions WHERE token_hash = $1`, tokenHash)
	return err
}

// GetSessionCSRF returns the CSRF token bound to a session token hash, or
// pgx.ErrNoRows when the session is absent or expired. The Session middleware
// uses it to validate the double-submit CSRF token on cookie-authenticated
// mutations.
func (db *DB) GetSessionCSRF(ctx context.Context, tokenHash string) (string, error) {
	var token string
	err := db.pool.QueryRow(ctx,
		`SELECT csrf_token FROM sessions WHERE token_hash = $1 AND expires_at > now()`,
		tokenHash).Scan(&token)
	return token, err
}

// DeleteExpiredSessions removes sessions whose expiry has passed.
func (db *DB) DeleteExpiredSessions(ctx context.Context) error {
	_, err := db.pool.Exec(ctx, `DELETE FROM sessions WHERE expires_at <= now()`)
	return err
}
