package store

import (
	"context"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

// CreateStoreInput carries the fields required to create a store. The row ID
// (UUID v4) is generated by the store layer; the slug is produced by the
// service layer (GenerateUniqueSlug) so it is passed in.
type CreateStoreInput struct {
	Name                string
	Slug                string
	Description         *string
	Address             string
	Phone               *string
	Latitude            *float64
	Longitude           *float64
	Specialty           string
	OwnerID             string
	Timezone            string
	SlotDuration        int
	MaxParallelBookings int
	MaxSlotsPerDay      int
	CancelationLimit    int
}

// UpdateStoreInput carries the fields that may change on a store. Nil pointer
// means "leave unchanged"; setting a nullable field to NULL is not supported
// in this phase.
type UpdateStoreInput struct {
	Name                *string
	Description         *string
	Address             *string
	Phone               *string
	Latitude            *float64
	Longitude           *float64
	Specialty           *string
	SlotDuration        *int
	MaxParallelBookings *int
	MaxSlotsPerDay      *int
	CancelationLimit    *int
	Suspended           *bool
}

// scanStore reads a single store row in the storeColumns order.
func scanStore(row pgx.Row) (Store, error) {
	var s Store
	err := row.Scan(
		&s.ID, &s.Name, &s.Slug, &s.Description, &s.Address, &s.Phone,
		&s.Latitude, &s.Longitude, &s.Specialty, &s.OwnerID, &s.Timezone,
		&s.SlotDuration, &s.MaxParallelBookings, &s.MaxSlotsPerDay,
		&s.CancelationLimit, &s.Suspended,
	)
	return s, err
}

// ListPublicStores returns stores matching the free-text query q (ILIKE over
// name/specialty/address) and the optional exact specialty filter, paginated.
// It also returns the total matching count.
func (db *DB) ListPublicStores(ctx context.Context, q, specialty string, limit, offset int) ([]Store, int, error) {
	where := `WHERE ($1 = '' OR name ILIKE '%' || $1 || '%'
		OR specialty ILIKE '%' || $1 || '%'
		OR address ILIKE '%' || $1 || '%')
		AND ($2 = '' OR specialty = $2)`

	var total int
	if err := db.pool.QueryRow(ctx, `SELECT count(*) FROM stores `+where, q, specialty).Scan(&total); err != nil {
		return nil, 0, err
	}

	rows, err := db.pool.Query(ctx, `SELECT `+storeColumns+` FROM stores `+where+`
		ORDER BY name LIMIT $3 OFFSET $4`, q, specialty, limit, offset)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	stores := []Store{}
	for rows.Next() {
		s, err := scanStore(rows)
		if err != nil {
			return nil, 0, err
		}
		stores = append(stores, s)
	}
	return stores, total, rows.Err()
}

// GetStoreBySlug returns the store with the given slug, or pgx.ErrNoRows.
func (db *DB) GetStoreBySlug(ctx context.Context, slug string) (Store, error) {
	row := db.pool.QueryRow(ctx, `SELECT `+storeColumns+` FROM stores WHERE slug = $1`, slug)
	return scanStore(row)
}

// GetStoreByID returns the store with the given id, or pgx.ErrNoRows.
func (db *DB) GetStoreByID(ctx context.Context, id string) (Store, error) {
	row := db.pool.QueryRow(ctx, `SELECT `+storeColumns+` FROM stores WHERE id = $1`, id)
	return scanStore(row)
}

// ListStoresByOwner returns all stores owned by the given user.
func (db *DB) ListStoresByOwner(ctx context.Context, ownerID string) ([]Store, error) {
	rows, err := db.pool.Query(ctx, `SELECT `+storeColumns+` FROM stores WHERE owner_id = $1 ORDER BY name`, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	stores := []Store{}
	for rows.Next() {
		s, err := scanStore(rows)
		if err != nil {
			return nil, err
		}
		stores = append(stores, s)
	}
	return stores, rows.Err()
}

// SlugExists reports whether a store already uses the given slug.
func (db *DB) SlugExists(ctx context.Context, slug string) (bool, error) {
	var exists bool
	err := db.pool.QueryRow(ctx, `SELECT EXISTS (SELECT 1 FROM stores WHERE slug = $1)`, slug).Scan(&exists)
	return exists, err
}

// CreateStore inserts a new store (generating its UUID v4 id) and returns it.
func (db *DB) CreateStore(ctx context.Context, in CreateStoreInput) (Store, error) {
	id := uuid.NewString()
	row := db.pool.QueryRow(ctx, `
		INSERT INTO stores (id, name, slug, description, address, phone, latitude,
			longitude, specialty, owner_id, timezone, slot_duration,
			max_parallel_bookings, max_slots_per_day, cancelation_limit)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
		RETURNING `+storeColumns,
		id, in.Name, in.Slug, in.Description, in.Address, in.Phone, in.Latitude,
		in.Longitude, in.Specialty, in.OwnerID, in.Timezone, in.SlotDuration,
		in.MaxParallelBookings, in.MaxSlotsPerDay, in.CancelationLimit,
	)
	return scanStore(row)
}

// UpdateStore applies a partial update to the store with the given id and
// returns the updated row. If no fields are set it returns the current row.
func (db *DB) UpdateStore(ctx context.Context, id string, in UpdateStoreInput) (Store, error) {
	sets := make([]string, 0, 12)
	args := []any{id}
	add := func(col string, val any) {
		args = append(args, val)
		sets = append(sets, fmt.Sprintf("%s = $%d", col, len(args)))
	}

	if in.Name != nil {
		add("name", *in.Name)
	}
	if in.Description != nil {
		add("description", *in.Description)
	}
	if in.Address != nil {
		add("address", *in.Address)
	}
	if in.Phone != nil {
		add("phone", *in.Phone)
	}
	if in.Latitude != nil {
		add("latitude", *in.Latitude)
	}
	if in.Longitude != nil {
		add("longitude", *in.Longitude)
	}
	if in.Specialty != nil {
		add("specialty", *in.Specialty)
	}
	if in.SlotDuration != nil {
		add("slot_duration", *in.SlotDuration)
	}
	if in.MaxParallelBookings != nil {
		add("max_parallel_bookings", *in.MaxParallelBookings)
	}
	if in.MaxSlotsPerDay != nil {
		add("max_slots_per_day", *in.MaxSlotsPerDay)
	}
	if in.CancelationLimit != nil {
		add("cancelation_limit", *in.CancelationLimit)
	}
	if in.Suspended != nil {
		add("suspended", *in.Suspended)
	}

	if len(sets) == 0 {
		return db.GetStoreByID(ctx, id)
	}

	sets = append(sets, "updated_at = now()")
	query := "UPDATE stores SET " + strings.Join(sets, ", ") + " WHERE id = $1 RETURNING " + storeColumns
	return scanStore(db.pool.QueryRow(ctx, query, args...))
}
