package store

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// Role is the authorization role persisted on users.role.
type Role string

const (
	RoleUser  Role = "USER"
	RoleOwner Role = "OWNER"
	RoleAdmin Role = "ADMIN"
)

// User is a single users row. PasswordHash is internal-only (never
// serialized); it is empty for users without credentials (e.g. the legacy
// bootstrap owner).
type User struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Email         string `json:"email"`
	Role          Role   `json:"role"`
	EmailVerified bool   `json:"emailVerified"`
	PasswordHash  string `json:"-"`
}

// Actor is the authenticated identity resolved from a session or the API-key
// bootstrap. It carries the subset of user data the HTTP layer needs for
// authorization.
type Actor struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Role  Role   `json:"role"`
}

// CreateUserInput carries the fields required to register a user. The row ID
// (UUID v4) is generated by the store layer.
type CreateUserInput struct {
	Name              string
	Email             string
	PasswordHash      string
	Role              Role
	VerificationToken string
}

const userColumns = `id, name, email, role, email_verified, password_hash`

// scanUser reads a single users row in the userColumns order. name, email and
// password_hash are nullable in the schema, so they scan through pointers.
func scanUser(row pgx.Row) (User, error) {
	var u User
	var name, email, passwordHash *string
	if err := row.Scan(&u.ID, &name, &email, &u.Role, &u.EmailVerified, &passwordHash); err != nil {
		return User{}, err
	}
	u.Name = strOrEmpty(name)
	u.Email = strOrEmpty(email)
	u.PasswordHash = strOrEmpty(passwordHash)
	return u, nil
}

// strOrEmpty dereferences a nullable text column, mapping NULL to "".
func strOrEmpty(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}

// CreateUser inserts a new user and returns the persisted row.
func (db *DB) CreateUser(ctx context.Context, in CreateUserInput) (User, error) {
	id := uuid.NewString()
	row := db.pool.QueryRow(ctx, `
		INSERT INTO users (id, name, email, role, email_verified, password_hash, verification_token)
		VALUES ($1, $2, $3, $4, false, $5, $6)
		RETURNING `+userColumns,
		id, in.Name, in.Email, in.Role, in.PasswordHash, in.VerificationToken)
	return scanUser(row)
}

// GetUserByEmail returns the user with the given email, or pgx.ErrNoRows.
func (db *DB) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := db.pool.QueryRow(ctx, `SELECT `+userColumns+` FROM users WHERE email = $1`, email)
	return scanUser(row)
}

// GetUserByID returns the user with the given id, or pgx.ErrNoRows.
func (db *DB) GetUserByID(ctx context.Context, id string) (User, error) {
	row := db.pool.QueryRow(ctx, `SELECT `+userColumns+` FROM users WHERE id = $1`, id)
	return scanUser(row)
}

// EnsureBootstrapOwner idempotently ensures the bootstrap owner user exists
// with the legacy id and configured email and role OWNER, so existing stores
// keep their ownership. It returns the persisted row.
func (db *DB) EnsureBootstrapOwner(ctx context.Context, id, email string) (User, error) {
	row := db.pool.QueryRow(ctx, `
		INSERT INTO users (id, name, email, role, email_verified)
		VALUES ($1, $2, $3, 'OWNER', false)
		ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, role = 'OWNER'
		RETURNING `+userColumns,
		id, "Dashboard Owner", email)
	return scanUser(row)
}

// IsUniqueViolation reports whether err is a PostgreSQL unique-constraint
// violation (SQLSTATE 23505), e.g. a duplicate users.email.
func IsUniqueViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23505"
}
